<?php

namespace App\Models;

use App\Events\UpdateCoordinatesEvent;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AdministrativeBoundary extends Model
{
    use HasFactory;

    protected $table = 'adminstrativeboundaries';

    protected $fillable = [
        'country',
        'country_id',
        'admin_bound_1',
        'admin_bound_2',
        'admin_bound_3',
        'coordinates',
        ];

    public function datasets()
    {
        return $this->belongsToMany(Dataset::class);
    }

    protected static function  boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function ($model){
            event(new UpdateCoordinatesEvent($model->country_id));
        });
    }
}
